name: Push to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Commit files
      run: |
        git config remote.origin.url https://github.com/cartolin/cartolin.github.io.git
        git config --local user.email "cartolin.fidel@gmail.com"
        git config --local user.name "cartolin"
        git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ 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 }}
        branch: ${{ main }}